
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS ROG
 */
public class kelas extends javax.swing.JFrame {

    /**
     * Creates new form kelas
     */
    public kelas() {
        initComponents();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        carijTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Carikelas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        ruangan = new javax.swing.JTextField();
        walikelasTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tingkat_kelasComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nama_kelas = new javax.swing.JTextField();
        jumlahTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jurusanComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Kembali = new javax.swing.JButton();
        tambahSiswa = new javax.swing.JButton();
        ubahSiswa = new javax.swing.JButton();
        HapusSiswa = new javax.swing.JButton();
        clearSiswa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        carijTextField.setBackground(new java.awt.Color(255, 255, 255));
        carijTextField.setForeground(new java.awt.Color(0, 0, 0));
        carijTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carijTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cari :");

        Carikelas.setBackground(new java.awt.Color(255, 255, 255));
        Carikelas.setForeground(new java.awt.Color(0, 0, 0));
        Carikelas.setText("Cari");
        Carikelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarikelasActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        ruangan.setBackground(new java.awt.Color(255, 255, 255));
        ruangan.setForeground(new java.awt.Color(0, 0, 0));

        walikelasTextField.setBackground(new java.awt.Color(255, 255, 255));
        walikelasTextField.setForeground(new java.awt.Color(0, 0, 0));
        walikelasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walikelasTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(86, 86, 86));
        jLabel5.setText("Tingkatan Kelas");

        tingkat_kelasComboBox.setBackground(new java.awt.Color(255, 255, 255));
        tingkat_kelasComboBox.setForeground(new java.awt.Color(0, 0, 0));
        tingkat_kelasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih tingkat kelas", "10", "11", "12" }));
        tingkat_kelasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tingkat_kelasComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(86, 86, 86));
        jLabel4.setText("Ruangan");

        nama_kelas.setBackground(new java.awt.Color(255, 255, 255));
        nama_kelas.setForeground(new java.awt.Color(0, 0, 0));

        jumlahTextField.setBackground(new java.awt.Color(255, 255, 255));
        jumlahTextField.setForeground(new java.awt.Color(0, 0, 0));
        jumlahTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(86, 86, 86));
        jLabel2.setText("Wali Kelas");

        jurusanComboBox.setBackground(new java.awt.Color(255, 255, 255));
        jurusanComboBox.setForeground(new java.awt.Color(0, 0, 0));
        jurusanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jurusan", "IPS", "IPA", "BAHASA" }));
        jurusanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(86, 86, 86));
        jLabel3.setText("Jumlah Siswa");

        jLabel1.setBackground(new java.awt.Color(86, 86, 86));
        jLabel1.setText("Nama Kelas");

        jLabel6.setBackground(new java.awt.Color(86, 86, 86));
        jLabel6.setText("Jurusan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tingkat_kelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(walikelasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ruangan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jurusanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(walikelasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tingkat_kelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jumlahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(jurusanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 153, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        Kembali.setBackground(new java.awt.Color(255, 255, 255));
        Kembali.setForeground(new java.awt.Color(0, 0, 0));
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        tambahSiswa.setBackground(new java.awt.Color(255, 255, 255));
        tambahSiswa.setForeground(new java.awt.Color(0, 0, 0));
        tambahSiswa.setText("Tambah");
        tambahSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahSiswaActionPerformed(evt);
            }
        });

        ubahSiswa.setBackground(new java.awt.Color(255, 255, 255));
        ubahSiswa.setForeground(new java.awt.Color(0, 0, 0));
        ubahSiswa.setText("Ubah");
        ubahSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahSiswaActionPerformed(evt);
            }
        });

        HapusSiswa.setBackground(new java.awt.Color(255, 255, 255));
        HapusSiswa.setForeground(new java.awt.Color(0, 0, 0));
        HapusSiswa.setText("Hapus");
        HapusSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusSiswaActionPerformed(evt);
            }
        });

        clearSiswa.setBackground(new java.awt.Color(255, 255, 255));
        clearSiswa.setForeground(new java.awt.Color(0, 0, 0));
        clearSiswa.setText("Clear");
        clearSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tambahSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ubahSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HapusSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tambahSiswa)
                .addGap(18, 18, 18)
                .addComponent(ubahSiswa)
                .addGap(18, 18, 18)
                .addComponent(HapusSiswa)
                .addGap(18, 18, 18)
                .addComponent(clearSiswa)
                .addGap(18, 18, 18)
                .addComponent(Kembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(carijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Carikelas)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carikelas)
                    .addComponent(carijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("SILAHKAN INPUT DATA KELAS");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("SELAMAT DATANG DI DATA KELAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(819, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void walikelasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walikelasTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_walikelasTextFieldActionPerformed

    private void tingkat_kelasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tingkat_kelasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tingkat_kelasComboBoxActionPerformed

    private void carijTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carijTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carijTextFieldActionPerformed

    private void CarikelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarikelasActionPerformed
        // TODO add your handling code here:
         try {
    // Buat koneksi ke database
    java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();

    // Query untuk mencari data berdasarkan nama kelas atau wali kelas
    String sql = "SELECT * FROM kelas WHERE nama_kelas = ? OR wali_kelas = ?";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);

    // Set parameter pencarian
    pst.setString(1, carijTextField.getText());
    pst.setString(2, carijTextField.getText());

    // Eksekusi query
    ResultSet rs = pst.executeQuery();

    // Jika data ditemukan
    if (rs.next()) {
        // Isi data ke form
        nama_kelas.setText(rs.getString("nama_kelas")); // Kolom nama_kelas
        walikelasTextField.setText(rs.getString("wali_kelas")); // Kolom wali_kelas
        String tingkat = rs.getString("tingkat_kelas"); // Kolom tingkat_kelas
        jumlahTextField.setText(rs.getString("jumlah_siswa"));
        ruangan.setText(rs.getString("ruangan"));
        String jurusan = rs.getString("jurusan");
        

        // Atur pilihan pada ComboBox berdasarkan tingkat
        if ("IPS".equalsIgnoreCase(jurusan)) {
            jurusanComboBox.setSelectedIndex(1); // Index 1 untuk 10
        } else if ("IPA".equalsIgnoreCase(jurusan)) {
            jurusanComboBox.setSelectedIndex(2); // Index 2 untuk 11
        } else if ("BAHASA".equalsIgnoreCase(jurusan)) {
            jurusanComboBox.setSelectedIndex(3); // Index 3 untuk 12
        } else {
            jurusanComboBox.setSelectedIndex(0); // Default: Tidak valid
        }
        
            if ("10".equalsIgnoreCase(tingkat)) {
            tingkat_kelasComboBox.setSelectedIndex(1); // Index 1 untuk 10
        } else if ("11".equalsIgnoreCase(tingkat)) {
            tingkat_kelasComboBox.setSelectedIndex(2); // Index 2 untuk 11
        } else if ("12".equalsIgnoreCase(tingkat)) {
            tingkat_kelasComboBox.setSelectedIndex(3); // Index 3 untuk 12
        } else {
            tingkat_kelasComboBox.setSelectedIndex(0); // Default: Tidak valid
        }


        // Fokuskan pada baris yang dicari di JTable
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel(); // Pastikan `jTable2` adalah JTable Anda
        boolean found = false; // Menandai apakah baris ditemukan
        for (int i = 0; i < model.getRowCount(); i++) {
            // Cocokkan data nama_kelas atau wali_kelas di JTable
            if (model.getValueAt(i, 1).toString().equalsIgnoreCase(carijTextField.getText()) ||
                model.getValueAt(i, 2).toString().equalsIgnoreCase(carijTextField.getText())) {
                jTable2.setRowSelectionInterval(i, i); // Pilih baris yang sesuai
                jTable2.scrollRectToVisible(jTable2.getCellRect(i, 0, true)); // Scroll ke baris tersebut
                found = true;
                break;
            }
        }
        
        JOptionPane.showMessageDialog(null, "Data Kelas " +carijTextField.getText()+" Ditemukan");
                tampil();
        
    } else {
        JOptionPane.showMessageDialog(null, "Data tidak ditemukan di database.");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    e.printStackTrace();
}

    }//GEN-LAST:event_CarikelasActionPerformed

    private void tambahSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahSiswaActionPerformed
        // TODO add your handling code here:
        try {
            String tingkat;
            switch (tingkat_kelasComboBox.getSelectedIndex()) {
                case 1:
                    tingkat="10";
                    break;
                case 2:
                    tingkat="11";
                    break;
                case 3:
                    tingkat="12";
                    break;
                default:
                    throw new Exception("tingkatan kelas tidak valid. Pilih '10' atau '11' atau '12'.");
                }   
                String sql = "insert into kelas (nama_kelas,wali_kelas,tingkat_kelas,jumlah_siswa,ruangan,jurusan) values('"
                        +nama_kelas.getText()+"','"
                        +walikelasTextField.getText()+"','"
                        +tingkat+"','"
                        +jumlahTextField.getText()+"','"
                        +ruangan.getText()+"','"
                        +jurusanComboBox.getSelectedItem()+"')";
                     java.sql.Connection conn=(java.sql.Connection) koneksi.koneksiDB();
                     java.sql.PreparedStatement pst= conn.prepareStatement(sql);
                     pst.execute();
                     JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
                     tampil();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Data Gagal disimpan");
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_tambahSiswaActionPerformed

    private void ubahSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahSiswaActionPerformed
        // TODO add your handling code here:
         try {
            // Validasi input
            if (nama_kelas.getText().isEmpty() || walikelasTextField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap lengkapi semua data!");
                return;
            }

            // Ambil nama saat ini (nama yang akan menjadi referensi untuk WHERE)
            String namaSekarang = carijTextField.getText();

            // Tentukan nilai kelamin berdasarkan index ComboBox
            String tingkat = "";
            switch (tingkat_kelasComboBox.getSelectedIndex()) {
                case 1 -> tingkat="10";
                case 2 -> tingkat="11";
                case 3 -> tingkat="12";
                default -> throw new Exception("tingkatan kelas tidak valid. Pilih '10' atau '11' atau '12'.");
                }
            
              String jurusan = "";
            switch (jurusanComboBox.getSelectedIndex()) {
                case 1 -> jurusan="IPS";
                case 2 -> jurusan="IPA";
                case 3 -> jurusan="BAHASA";
                default -> throw new Exception("jurusan tidak valid. Pilih 'IPA' atau 'IPS' atau 'BAHASA'.");
                }   

            // Koneksi ke database
            java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();

            // Query SQL untuk memperbarui data siswa berdasarkan nama
            String sql = "UPDATE kelas SET nama_kelas=?, wali_kelas=?, tingkat_kelas=?, jumlah_siswa=?,ruangan=?,jurusan=? WHERE nama_kelas=?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Isi parameter ke dalam query
            pst.setString(1, nama_kelas.getText()); // Nama baru
            pst.setString(2, walikelasTextField.getText());
            pst.setString(3, tingkat);
            pst.setString(4,jumlahTextField.getText()) ;
            pst.setString(5, ruangan.getText());
            pst.setString(6,jurusan);
            pst.setString(7, namaSekarang); // Nama saat ini sebagai referensi untuk WHERE

            // Eksekusi query
            int rowsAffected = pst.executeUpdate();

            // Notifikasi hasil
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui");
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan atau tidak berhasil diperbarui");
            }

            // Panggil metode untuk memperbarui tampilan data
            tampil();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal diperbarui: " + e.getMessage());
            e.printStackTrace();
        }

        
    }//GEN-LAST:event_ubahSiswaActionPerformed

    private void HapusSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusSiswaActionPerformed
        // TODO add your handling code here:
         try {
            // Koneksi ke database
            java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();

            // Query SQL untuk menghapus data berdasarkan nama
            String sql = "DELETE FROM kelas WHERE nama_kelas = ?";

            // Persiapkan statement
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Set nilai parameter (nama kelas)
            pst.setString(1, nama_kelas.getText());

            // Eksekusi query
            int rowsAffected = pst.executeUpdate();

            // Beri notifikasi berdasarkan hasil eksekusi
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan atau tidak berhasil dihapus");
            }

            // Panggil metode untuk memperbarui tampilan data (misalnya JTable)
            tampil();
         } catch (Exception e) {
        // Tampilkan pesan kesalahan
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        e.printStackTrace();
        }
    }//GEN-LAST:event_HapusSiswaActionPerformed

    private void clearSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSiswaActionPerformed
        // TODO add your handling code here:
        walikelasTextField.setText("");
        nama_kelas.setText("");
        tingkat_kelasComboBox.setSelectedIndex(0);
        jumlahTextField.setText("");
        ruangan.setText("");
        jurusanComboBox.setSelectedIndex(0);

    }//GEN-LAST:event_clearSiswaActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);

        this.dispose();

    }//GEN-LAST:event_KembaliActionPerformed

    private void jumlahTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahTextFieldActionPerformed

    private void jurusanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusanComboBoxActionPerformed

        public void tampil(){
            try {
                  DefaultTableModel tabel = new DefaultTableModel();
                    tabel.addColumn("Nama Kelas");
                    tabel.addColumn("Tingkatan Kelas");
                    tabel.addColumn("Wali Kelas");
                    tabel.addColumn("Jurusan");
                    tabel.addColumn("Jumlah Siswa");
                    tabel.addColumn("Ruangan");
                    java.sql.Connection conn=(java.sql.Connection) koneksi.koneksiDB();
                    String sql= "SELECT * FROM kelas";
                    java.sql.PreparedStatement pst= conn.prepareStatement(sql);
                    ResultSet rs = pst.executeQuery(sql);
                    while (rs.next()){
                        tabel.addRow(new Object[]{
                        rs.getString(2),
                        rs.getString(4),
                        rs.getString(3),
                        rs.getString(7),
                        rs.getInt(5),
                        rs.getString(6),
                        
                        });
                        jTable2.setModel(tabel);
                    }

                
            } catch (Exception e) {
                System.out.println("error : "+ e.getMessage());
            }
        
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carikelas;
    private javax.swing.JButton HapusSiswa;
    private javax.swing.JButton Kembali;
    private javax.swing.JTextField carijTextField;
    private javax.swing.JButton clearSiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jumlahTextField;
    private javax.swing.JComboBox<String> jurusanComboBox;
    private javax.swing.JTextField nama_kelas;
    private javax.swing.JTextField ruangan;
    private javax.swing.JButton tambahSiswa;
    private javax.swing.JComboBox<String> tingkat_kelasComboBox;
    private javax.swing.JButton ubahSiswa;
    private javax.swing.JTextField walikelasTextField;
    // End of variables declaration//GEN-END:variables
}
